name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Deploy app
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/goldenowl-app:latest
          docker stop goldenowl || true
          docker rm goldenowl || true
          docker run -d --name goldenowl -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/goldenowl-app:latest